services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - plugins.security.disabled=true
    depends_on:
      - opensearch

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  listing-svc:
    image: demo/listing-svc:latest
    build:
      context: .
      dockerfile: src/Services/ListingService/API/ListingService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=listings
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
      - VSTEST_HOST_DEBUG=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://+:5001
      - ApplicationConfiguration__RabbitMQSettings__Host=rabbitmq
      - ApplicationConfiguration__PostgresSqlSettings__ConnectionString=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=listings
    ports:
      - 5001:5001
    volumes:
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - .:/src
    depends_on:
      postgres:
        condition: service_healthy

  search-svc:
    image: demo/search-svc:latest
    build:
      context: .
      dockerfile: src/Services/SearchService/API/SearchService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - OpenSearch__Uri=http://opensearch:9200
      - ApplicationConfiguration__RabbitMQSettings__Host=rabbitmq
      - ApplicationConfiguration__MongoDbSettings__ConnectionString=mongodb://root:mongopw@mongodb:27017
      - ApplicationConfiguration__OpenSearchSettings__Uri=http://opensearch:9200
    ports:
      - 5002:5002
    depends_on:
      opensearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  auth-svc:
    image: demo/auth-svc:latest
    build:
      context: .
      dockerfile: src/Services/AuthenticationService/API/AuthenticationService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - AuthenticationService__ConnectionString=Server=postgres;Database=MarketplaceAuth;User Id=postgres;Password=postgrespw;
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy

  document-processor:
    image: demo/document-processor:latest
    build:
      context: .
      dockerfile: src/Functions/DocumentProcessor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - PostgresSqlSettings__ConnectionString=Server=postgres:5432;Database=hangfire;User Id=postgres;Password=postgrespw;
      - RabbitMQSettings__Host=rabbitmq
      - MongoDbSettings__ConnectionString=mongodb://root:mongopw@mongodb:27017
      - MinIOSettings__Endpoint=minio:9000
    ports:
      - 5003:5003
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      minio:
        condition: service_started

volumes:
  postgres-data:
  opensearch-data:
  rabbitmq-data:
  minio-data:
  mongodb-data:
