services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - plugins.security.disabled=true
    depends_on:
      - opensearch

  listing-svc:
    image: demo/listing-svc:latest
    build:
      context: .
      dockerfile: src/Services/ListingService/API/ListingService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=listings
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
      - VSTEST_HOST_DEBUG=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://+:5001
    ports:
      - 5001:5001
    volumes:
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - .:/src
    depends_on:
      - postgres

  search-svc:
    image: demo/search-svc:latest
    build:
      context: .
      dockerfile: src/Services/SearchService/API/SearchService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - OpenSearch__Uri=http://opensearch:9200
    ports:
      - 5002:5002
    depends_on:
      - opensearch

  auth-svc:
    image: demo/auth-svc:latest
    build:
      context: .
      dockerfile: src/Services/AuthenticationService/API/AuthenticationService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - AuthenticationService__ConnectionString=Server=postgres;Database=MarketplaceAuth;User Id=postgres;Password=postgrespw;
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  postgres-data:
  opensearch-data:
